# Generated by Django 5.2.7 on 2025-12-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='creator_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
