# Generated by Django 5.2.8 on 2025-12-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_professor_creator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='creator_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
